# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SDSC SciComp
tagline:          'Scientific computing at SDSC'
description:      'Scientific computing applications group at the <a href="http://www.sdsc.edu" target="_blank">San Diego Supercomputer Center</a> at <a href="http://www.ucsd.edu" target="_blank">UC San Diego</a>.'
url:              http://scicomp.sdsc.edu
#url:              http://localhost:4000
baseurl:          /

author:
  name:           'Andrea Zonca'
  url:            https://twitter.com/andreazonca

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
